Add explanation of the keyword 'today'
Altinn/altinn-cdn pull request #64
Opened 2021-11-03 13:59 UTC by DanRJ

https://github.com/Altinn/altinn-studio/issues/7228

2021-11-04 10:32 UTC, lorang92 requested changes

2021-11-04 10:32 UTC, lorang92 commented on schemas/json/layout/layout.schema.v1.json
> +          "description": "Sets the minimum allowed date. Can also use keywords such as 'today'. The 'today' keyword will disable all past dates dynamically. Defaults to 1900-01-01T12:00:00.000Z'.",
`Can also use keywords such as 'today'. The 'today' keyword will disable all past dates dynamically.`
This makes is sound like we support other keywords. I suggest we only reference the once we actually support, and update this if the need be in the future.

Better with something like this?

```suggestion
          "description": "Sets the minimum allowed date. Can also use keyword 'today' to disable all past dates dynamically based on the current date. Defaults to 1900-01-01T12:00:00.000Z'.",
```

2021-11-05 07:35 UTC, lorang92 requested changes

2021-11-05 07:35 UTC, lorang92 commented on schemas/json/layout/layout.schema.v1.json
> +          "description": "Sets the maxiumum allowed date. Can also use keywords such as 'today'. The 'today' keyword will disable all future dates dynamically. Defaults to 2100-01-01T12:00:00.000Z.'"
Same fix as suggested her.

2021-11-05 08:31 UTC, DanRJ commented on schemas/json/layout/layout.schema.v1.json
> +          "description": "Sets the maxiumum allowed date. Can also use keywords such as 'today'. The 'today' keyword will disable all future dates dynamically. Defaults to 2100-01-01T12:00:00.000Z.'"
Fixed

2021-11-08 07:44 UTC, lorang92 approved these changes

2021-11-08 07:48 UTC, SandGrainOne approved these changes

2021-11-08 07:50 UTC, SandGrainOne reviewed
Is this ' character necessary?
Both descriptions has an extra ' character at the end. Doesn't look right.

2021-11-08 09:06 UTC, DanRJ commented
> Is this ' character necessary? Both descriptions has an extra ' character at the end. Doesn't look right.

I didnt see that one until you pointed it out, I think its missing one in the beginning of the date time example, e.g: '1900-...', however there is a couple of different ways used to display values in this file already, \"value\", or 'value' or no special characters at all, value.

How would you prefer it? @SandGrainOne @lorang92

2021-11-08 09:14 UTC, SandGrainOne commented
> How would you prefer it? @SandGrainOne @lorang92
I don't think the quotes adds anything here. At least not in VS code. My suggestion is to remove the unnecessary quote character.

2021-11-08 09:53 UTC, merged